### ISSUE TITLE
No matter what image is selected, the program will report the same error: "ValueError: not enough values to unpack"

### ISSUE THREAD

**Issue by SavageChigga** [dibrale/samist#4] opened 2023-06-09 11:35 UTC
I created a virtual environment named "samist" and followed the instructions as the readme file. But only succeed once at the first I run it. After that, whatever the picture or  model I choose, the program will always show the error as follows:
(samist) E:\samist>python main.py
Starting Segment Anything Model Image Segmentation Tool (SAMIST)
Traceback (most recent call last):
  File "E:\samist\main.py", line 302, in <module>
    [masks, [out_bw, out_full_res, masked_images, out_cropped]] = values[event]
ValueError: not enough values to unpack (expected 4, got 0)

**Comment by dibrale** [comment] 2023-06-09 16:38
Hello @SavageChigga,

I cannot reproduce your issue in my development environment. However, I have pushed a commit that will write a bit of extra debug information to help narrow down the problem. Please reproduce your issue with the new version of the script and let me know what console output you get.

**Comment by SavageChigga** [comment] 2023-06-12 01:33
Hello Alexander,

Thanks for taking time to help about this. I used the newest version you committed and the error information is as follows. It seems that the program is out of memory.  I'm using Nvidia RTX 2060 which has 6GB of memory and I don't konw if this is the reason why the program cannot be run correctly.

Starting Segment Anything Model Image Segmentation Tool (SAMIST)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 6.00 GiB total capacity; 4.60 GiB already allocated; 0 bytes free; 4.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "E:\samist\main.py", line 305, in <module>
    [masks, [out_bw, out_full_res, masked_images, out_cropped]] = values[event]
ValueError: not enough values to unpack (expected 4, got 0)

**Comment by dibrale** [comment] 2023-06-12 02:02
Hello, @SavageChigga,

VRAM is indeed the issue here. In my testing, running the smallest vit_b model requires a total of 3.8 GB, while running the largest vit_h model requires 6.3 GB. Running the vit_h model is clearly out of reach for your 2060. However, you can try running SAMIST using the vit_b (or maybe vit_l) model. If neither of those work using CUDA, cpu execution may be an option if you are willing to wait the length of a coffee break for the process to complete. You can also reduce the number of points per side to speed up the segmentation process.

I am closing this thread for the time being, but please don't hesitate to reach out if you have any other questions or concerns.

**Closed as completed by dibrale** 2023-06-12 02:02 UTC
Labels: bug
